skip_tags: true
init:
  - ps: ''
services:
  - mssql2014
  - iis
hosts:
  www.mydrupalsite.com: 127.0.0.1
image:
  - Visual Studio 2017
install:
  - cmd: net start MSSQL$SQL2014
  - ps: Set-Service 'SQLAgent$SQL2014' -StartupType Manual
  - ps: Start-Service W3SVC
  - ps: choco install php -y --no-progress
  - ps: choco install urlrewrite -y --no-progress
  - ps: choco install OpenSSL.Light -y --no-progress
  - ps: |
      $WorkingDir = Convert-Path .
      $ZipPath = Join-Path $WorkingDir '\chef_cmdlet.zip'
      (New-Object Net.WebClient).DownloadFile('https://ci.appveyor.com/api/projects/David19767/iischef/artifacts/iischef.cmdlet.zip?branch=1.x', $ZipPath)
      $DESTINATION= Join-Path $env:ProgramFiles "\WindowsPowerShell\Modules\Chef"
      New-Item -ItemType directory -Force -Path $DESTINATION
      (new-object -com shell.application).namespace($DESTINATION).CopyHere((new-object -com shell.application).namespace($ZipPath).Items(),16)
      Remove-Item $ZipPath
  - ps: $Env:Path = "C:\Program Files\OpenSSL;" + $Env:Path;
  - cmd: sc config wuauserv start= auto
  - cmd: net start wuauserv
  - ps: new-item c:\composer -itemtype directory
  - ps: $Env:Path = "C:\tools\php73;" + $Env:Path;
  - ps: Add-Content C:\tools\php73\php.ini "extension=php_openssl `n"
  - ps: Add-Content C:\tools\php73\php.ini "extension=php_mbstring `n"
  - ps: Add-Content C:\tools\php73\php.ini "extension=php_curl `n"
  - cmd: cd /d C:\composer
  - cmd: php -r "readfile('http://getcomposer.org/installer');" | php
  - ps: php C:\composer\composer.phar ' + $([char]37) + '*' | Out-File C:\composer\composer.bat -Encoding ASCII
  - cmd: SET PATH=C:\composer;%PATH%
  - ps: composer global require hirak/prestissimo
  - cmd: IF NOT EXIST C:\projects\drupal-project composer create-project -n drupal-composer/drupal-project:8.x-dev
  - cmd: cd /d C:\projects\drupal-project
  - cmd: composer config repositories.drupal composer https://packages.drupal.org/8
  - cmd: composer update drupal/core 8.3@dev
  - cmd: composer require drupal/sqlsrv:dev-2.x@dev
  - cmd: xcopy /S /I /E /Y %cd%\web\modules\contrib\sqlsrv\drivers %cd%\web\drivers
  - cmd: composer config repositories.1 git https://%GITLABUSERNAME%:%GITLABPASSWORD%@gitlab.com/david-garcia-garcia/mssql.git
  - cmd: composer require david/mssql
  - ps: php %cd%\vendor\drupal\console\bin\drupal ' + $([char]37) + '*' | Out-File %cd%/web/drupal.bat -Encoding ASCII
  - cmd: cd /d C:\projects\drupal-project\web
  - cmd: drupal about
  - cmd: drupal site:install standard --langcode="en" --db-type="sqlsrv" --db-host="localhost\SQL2014" --db-name="mydrupalsite" --db-user="sa" --db-pass="Password12!" --db-port="1433" --site-name="SQL Server Drupal Site" --site-mail="admin@example.com" --account-name="admin" --account-mail="admin@example.com" --account-pass="admin" --no-interaction
  - cmd: cd /d C:\projects\drupal-project
  - ps: (New-Object Net.WebClient).DownloadFile('https://www.drupal.org/files/issues/use_the_php_binary-2748883-15.patch','%cd%\patch.patch')
  - cmd: git apply patch.patch --directory=web
  - ps: (New-Object Net.WebClient).DownloadFile('https://www.drupal.org/files/issues/simpletest_is_broken_on-2605284-107.patch','%cd%\patch.patch') 
  - cmd: git apply patch.patch --directory=web
  - cmd: cd /d C:\projects\drupal-project\web
  - cmd: drupal module:install simpletest
  - ps: wget http://www.mysite.com/"
test_script:
  - cmd: cd /d C:\projects\drupal-project
  - cmd: mkdir c:\testresults\
  - cmd: php web/core/scripts/run-tests.sh --php php --verbose --url "http://www.mysite.com/" --xml c:\testresults\ "Common" --class Drupal\sqlsrv\Tests\SchemaTest
  - cmd: php web/core/scripts/run-tests.sh --php php --verbose --url "http://www.mysite.com/" --xml c:\testresults\ "Common" --class Drupal\sqlsrv\Tests\SelectQueryTest